
import React, { useMemo, useState, useEffect } from 'react';
import { soundManager } from '../services/soundManager';
import { Tag, Sparkles, AlertCircle, Clock, CheckCircle2, MessageSquare, Zap, Truck, FastForward, ShoppingCart } from 'lucide-react';
import { ChristmasIdea } from '../types';
import { generateBudgetChristmasIdea } from '../services/geminiService';

interface GiftTruckProps {
  onOpen: (idea: ChristmasIdea) => void;
  forcedDepartureTrigger?: number;
}

const GiftTruck: React.FC<GiftTruckProps> = ({ onOpen, forcedDepartureTrigger }) => {
  const [isLoading, setIsLoading] = useState(false);
  const [orderTotal, setOrderTotal] = useState(0);
  const [isLeaving, setIsLeaving] = useState(false);
  const [messageIndex, setMessageIndex] = useState(0);
  const [isVisible, setIsVisible] = useState(true);
  const [blink, setBlink] = useState(false);

  const TRUCK_LIMIT = 10;

  const messages = useMemo(() => [
    `⚠️ STATUS: Quantum Truck at ${orderTotal}$`,
    "🚨 AI LOGISTICS: Loading Magic Data...",
    "💎 NEON DEALS: Budget ideas $1-$5!",
    "📦 CARGO: 99% Christmas Spirit!",
    `🛣️ ${Math.max(0, TRUCK_LIMIT - orderTotal)}$ to HYPERSPEED!`,
    "🔔 Honk for Instant Miracles!",
    "🚀 FASTEST DELIVERY IN THE NORTH POLE",
    "🛑 WARNING: Engine Revving!",
    "🎁 Cyber-Gifts generated by Gemini AI"
  ], [orderTotal]);

  useEffect(() => {
    if (forcedDepartureTrigger && forcedDepartureTrigger > 0 && isVisible && !isLeaving) {
      triggerDeparture();
    }
  }, [forcedDepartureTrigger]);

  useEffect(() => {
    const interval = setInterval(() => {
      setMessageIndex((prev) => (prev + 1) % messages.length);
    }, 4000);
    return () => clearInterval(interval);
  }, [messages.length]);

  useEffect(() => {
    const interval = setInterval(() => {
      setBlink(prev => !prev);
    }, 300);
    return () => clearInterval(interval);
  }, []);

  const handleTruckClick = async () => {
    if (isLoading || isLeaving || !isVisible) return;
    
    // Multi-layered sound effects for the interaction
    soundManager.playClick();
    soundManager.playEngineRev();
    soundManager.playTruckHorn();
    
    setIsLoading(true);

    try {
      const price = Math.floor(Math.random() * 5) + 1;
      const idea = await generateBudgetChristmasIdea();
      const newTotal = orderTotal + price;
      setOrderTotal(newTotal);
      soundManager.playGiftOpen();
      onOpen(idea);

      if (newTotal >= TRUCK_LIMIT) {
        triggerDeparture();
      }
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  const triggerDeparture = () => {
    setIsLeaving(true);
    setTimeout(() => {
      soundManager.playWhoosh();
      setIsVisible(false);
      setTimeout(() => {
        setOrderTotal(0);
        setIsLeaving(false);
        setIsVisible(true);
        soundManager.playEngineRev();
        soundManager.playTruckHorn();
      }, 12000);
    }, 1500);
  };

  if (!isVisible) return (
    <div className="absolute bottom-10 left-10 z-40 animate-fade-in">
      <div className="bg-indigo-950/90 backdrop-blur-2xl px-6 py-4 rounded-[2rem] border-2 border-indigo-400/30 shadow-[0_0_40px_rgba(79,70,229,0.4)] text-white flex items-center gap-4">
        <div className="bg-indigo-500/20 p-3 rounded-full animate-spin">
          <Zap className="text-yellow-400" size={24} />
        </div>
        <div>
          <p className="font-black text-xs uppercase tracking-widest text-indigo-300">In Transit</p>
          <p className="text-[10px] text-white/40 italic">Hyper-Delivery in progress...</p>
        </div>
      </div>
    </div>
  );

  return (
    <div className={`absolute bottom-10 left-10 z-40 transition-all duration-1000 ease-in-out ${isLeaving ? 'translate-x-[150vw] opacity-0 skew-x-12' : 'translate-x-0 opacity-100'}`}>
      <div className="relative group">
        
        {/* Neon Message Bubble */}
        <div className="absolute -top-20 left-10 w-64 animate-bounce-subtle pointer-events-none z-50">
          <div className="bg-[#0f172a]/90 backdrop-blur-xl p-4 rounded-2xl rounded-bl-none border-2 border-indigo-500/40 shadow-2xl text-[10px] font-black uppercase tracking-widest text-indigo-100 flex items-center gap-3">
             <div className="bg-indigo-600 p-1.5 rounded-lg shrink-0">
               <Zap size={14} className="text-white fill-current" />
             </div>
             {isLeaving ? "WARP DRIVE ACTIVE!" : messages[messageIndex]}
          </div>
        </div>

        {/* Floating "BUY NOW" badge on hover */}
        <div className="absolute -top-8 left-1/2 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-all duration-300 pointer-events-none z-50 scale-75 group-hover:scale-100">
           <div className="bg-red-600 text-white font-black px-4 py-1.5 rounded-full border-2 border-white shadow-[0_0_20px_rgba(220,38,38,0.6)] flex items-center gap-2 whitespace-nowrap">
              <ShoppingCart size={14} fill="currentColor" /> BUY NOW
           </div>
        </div>

        <button 
          onClick={handleTruckClick}
          disabled={isLoading || isLeaving}
          className={`relative flex flex-col items-center group pointer-events-auto transition-all ${isLoading ? 'animate-shake-vibrate' : ''}`}
        >
          <div className="relative flex items-end">
            {/* Cyber Glows */}
            <div className={`absolute -right-24 bottom-6 w-48 h-24 bg-gradient-to-r from-indigo-500/40 to-transparent blur-3xl transition-opacity ${blink ? 'opacity-100' : 'opacity-40'}`} />
            
            <div className="text-8xl md:text-9xl drop-shadow-[0_0_30px_rgba(79,70,229,0.5)] select-none flex items-end relative transition-transform group-hover:scale-105 active:scale-95">
              <span className="scale-x-[-1] inline-block">🚛</span>
              
              {/* Neon Headlights */}
              <div className={`absolute right-4 bottom-14 w-3 h-3 bg-cyan-400 rounded-full shadow-[0_0_20px_#22d3ee] transition-opacity ${blink ? 'opacity-100' : 'opacity-40'}`} />
              
              {/* Cargo packages with glow */}
              <div className="absolute -top-10 right-12 flex gap-1">
                 <span className="text-3xl drop-shadow-[0_0_10px_white] animate-float">🎁</span>
                 <span className="text-3xl drop-shadow-[0_0_10px_white] animate-float" style={{ animationDelay: '0.5s' }}>📦</span>
              </div>
            </div>

            {/* Tactical HUD Overlay */}
            <div className="absolute -bottom-14 left-0 w-full bg-[#0f172a]/80 backdrop-blur-md p-3 rounded-2xl border border-indigo-500/30 shadow-2xl">
              <div className="flex justify-between items-center text-[8px] font-black uppercase tracking-widest text-indigo-300 mb-1">
                <span>Magic Load: {orderTotal}u</span>
                <span>Max: {TRUCK_LIMIT}u</span>
              </div>
              <div className="h-1.5 w-full bg-black/50 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-indigo-600 to-cyan-400 transition-all duration-700 shadow-[0_0_10px_rgba(79,70,229,1)]"
                  style={{ width: `${(orderTotal / TRUCK_LIMIT) * 100}%` }}
                />
              </div>
            </div>
          </div>
          
          {/* Ground Reflection */}
          <div className="w-32 h-4 bg-indigo-500/10 blur-xl rounded-full mt-12 group-hover:scale-x-125 transition-transform" />
        </button>
      </div>

      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-10px); }
        }
        .animate-float { animation: float 3s ease-in-out infinite; }
        
        @keyframes shake-vibrate {
          0%, 100% { transform: translate(0, 0); }
          10%, 30%, 50%, 70%, 90% { transform: translate(-1px, 1px); }
          20%, 40%, 60%, 80% { transform: translate(1px, -1px); }
        }
        .animate-shake-vibrate { animation: shake-vibrate 0.1s linear infinite; }
      `}</style>
    </div>
  );
};

export default GiftTruck;
